import json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
def write(path,data): (root/path).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
p={}
def field(key,title,typ,description,default=None,**kw):
 d={'title':title,'type':typ,'description':description}
 if default is not None:d['default']=default
 if typ=='string':d['editor']='textfield'
 if typ=='array':d.update(editor='stringList',items={'type':'string'})
 if typ=='object':d['editor']='json'
 d.update(kw);p[key]=d
field('advertisers','Advertiser handles or IDs','array','Accounts to inspect. Accepts handles, @handles, public x.com/twitter.com profile URLs, and numeric user IDs. Maximum 200. This source does not support global content search.',prefill=['Nike'],maxItems=200,sectionCaption='Scope',sectionDescription='X discloses ads served in supported EU markets. Enter advertiser accounts first.')
field('countries','Countries where ads were served','array','ISO alpha-2 served-country codes. Validated against live supported countries. UK/EEA coverage is not assumed. Ignored for a named market preset.',['FR'])
field('marketPreset','Market preset','string','Expand a region to supported served countries. Unsupported members such as CH or GB are skipped with a warning.','Custom',editor='select',enum=['EU27','DACH','Nordics','Benelux','UK & Ireland','All supported','Custom'])
field('startDate','Delivery period starts','string','UTC day or relative date (e.g. 90 days). Clamped to the source minimum. Defaults to the last 90 days.','90 days',editor='datepicker',dateType='absoluteOrRelative')
field('endDate','Delivery period ends','string','Inclusive UTC day or relative date. 0 days means today. Future dates clamp to today.','0 days',editor='datepicker',dateType='absoluteOrRelative')
field('keywords','Include keywords or phrases','array','Match words, quoted phrases, or /RE2 regex/. Runs after enrichment when server-side search is unavailable.',[],sectionCaption='Filters',sectionDescription='Unknown fields are kept with filterUncertain unless strict filtering is enabled. Exclusions always win.')
field('excludeKeywords','Exclude keywords or phrases','array','Drop known matches before positive keyword matching. Supports quoted phrases and /regex/.',[])
field('keywordMatch','Keyword match rule','string','Any matches at least one include expression; all requires every include expression.','any',editor='select',enum=['any','all'])
field('keywordFields','Fields searched by keywords','array','Creative text, advertiser identity, disclosed targeting and landing URL. Selecting creativeText automatically enables creative enrichment.',['creativeText','advertiser','targeting','landingUrl'],editor='select',items={'type':'string','enum':['creativeText','advertiser','targeting','landingUrl']})
field('caseSensitive','Match case exactly','boolean','When off, Unicode compatibility/diacritic folding and case folding support European-language matching.',False)
field('targetedLocations','Disclosed geo-targeting','array','Strings matched against disclosed target locations, distinct from the country where the ad was served.',[])
for k,t,d in [('minImpressions','Minimum impressions','Keep rows with at least this many disclosed impressions.'),('minReach','Minimum unique reach','Keep rows with at least this disclosed reach. Unique reach cannot be summed across chunks.')]:field(k,t,'number',d,nullable=True,minimum=0)
field('approvalStatuses','Approval statuses','array','Free text, compared without case. Suggested source values include Verified and Halted; new values remain usable.',[])
field('fundingTypes','Funding instrument types','array','Free-text disclosed funding types, compared without case. No payment-person lookup is performed.',[])
field('mediaTypes','Creative media types','array','Experimental media metadata must be disclosed by repository/embed/API. Unknown is not treated as text.',[],editor='select',items={'type':'string','enum':['text','image','video','gif','carousel','unknown']})
field('strictFilters','Drop rows with unknown filtered fields','boolean','When on, unavailable fields cannot satisfy a filter. When off, undecidable matches are kept with filterUncertain=true.',False)
field('enrichCreatives','Enrich public post text','boolean','Fetch public oEmbed text, author and links per unique tweet ID. Deleted/protected posts retain repository metrics.',True,sectionCaption='Enrichment')
field('resolveLandingUrls','Resolve landing URLs','boolean','Follow disclosed t.co links with bounded redirects, strict timeouts and public-destination checks; extract domain and UTM fields.',True)
field('lookupMedia','Experimental media lookup','boolean','Best-effort asset details through official X API v2 with a supplied token, otherwise public embed metadata. Failures never remove repository metrics.',False)
field('xBearerToken','X developer bearer token','string','Optional permitted developer app bearer token. Required for direct documented export mode and official API media lookups. Never logged.',isSecret=True)
field('mode','Run mode','string','Snapshot emits matching ads without reading/writing monitor state. Monitor emits only NEW, CHANGED and REMOVED.','snapshot',editor='select',enum=['snapshot','monitor'],sectionCaption='Monitoring and notifications')
field('monitorKey','Monitor identity','string','Optional stable label hashed for state keys. Otherwise derived from advertiser/country/filter inputs. Keep the same value in your scheduled task.')
field('monitorStoreName','Named monitor state store','string','Persistent named Apify KVS. State is sharded by advertiser, country and ad-key bucket. Schedule overlapping runs sequentially.','x-ads-monitor-state')
field('notifyOn','Notify on these events','array','One digest per run for selected material campaign events.',['NEW','CHANGED','REMOVED'],editor='select',items={'type':'string','enum':['NEW','CHANGED','REMOVED']})
field('removalGraceRuns','Complete runs before removal','integer','Absent campaigns are removed only after this many fully successful runs of the same scope. Partial/failed queries never increment absence.',2,minimum=1,maximum=100)
field('metricChangeThresholdPercent','Metric-change threshold (%)','number','Null means impression/reach growth alone is not a material change. Set a percentage to include significant changes relative to the previous observation.',nullable=True,minimum=0)
for k,t,d in [('webhookUrl','Generic webhook URL','HTTPS digest endpoint. Gets full emitted-event JSON and X-X-Ads-Signature: sha256=<HMAC>.'),('webhookSecret','Webhook HMAC secret','Required with webhookUrl. HMAC-SHA256 signs the exact UTF-8 request body.'),('slackWebhookUrl','Slack incoming webhook URL','Optional Slack incoming webhook endpoint. Gets native Block Kit digest formatting.'),('discordWebhookUrl','Discord webhook URL','Optional Discord endpoint. Gets a native embed digest.')]:field(k,t,'string',d,isSecret=True)
field('notifyMaxItems','Maximum ads in channel digest','integer','Limit displayed top ads in Slack/Discord and generic highlights. Generic full events remain available in the linked dataset.',10,minimum=1,maximum=100)
field('notifyOnEmpty','Send an empty digest','boolean','Send a summary even when no selected campaign event was emitted.',False)
field('exportFormats','Generate download files','array','Files in the run KVS: BOM CSV, JSON, streaming Excel, and self-contained HTML. Native dataset export is always available.',['csv','json','xlsx','html'],editor='select',items={'type':'string','enum':['csv','json','xlsx','html']},sectionCaption='Output and performance')
field('includeRaw','Include original source rows','boolean','Keep raw repository rows for auditing. Increases storage/export sizes.',False)
field('sortBy','Result order','string','Sort final emitted results on disk. Unknown metrics sort last.','impressions',editor='select',enum=['impressions','reach','recency','advertiser'])
for k,t in [('maxAdsPerAdvertiser','Maximum emitted ads per advertiser'),('maxItems','Maximum emitted ads overall')]:field(k,t,'integer','Null means no output cap. A cap never justifies removal inference; un-emitted new/change events remain pending for the next run.',nullable=True,minimum=1)
field('sourceMode','Source adapter','string','Auto probes the best verified working source. API is a documented stub until a new official API is verified; export needs a permitted bearer token.','auto',editor='select',enum=['auto','export','api','ui'])
field('enablePublicUiTransport','Enable public UI HTTP service','boolean','Feature flag for anonymous endpoints discovered in current public-page assets. They are not a documented API. Logs a warning and falls back to anonymous browser/export if unavailable.',True)
for k,t,d,default,lo,hi in [('concurrency','Concurrent source queries','Polite default is two jobs. Lower to one when the source is slow or rate limited.',2,1,10),('requestDelayMs','Minimum request spacing per host (ms)','Token-bucket host pacing shared by repository, enrichment and notifications.',1000,0,60000),('maxRetries','Maximum request retries','Bounded retries with exponential backoff/jitter for retryable errors. Auth/invalid queries do not retry.',3,0,10),('jobTimeoutMinutes','Export job timeout (minutes)','Maximum time for a submitted CSV job; polling is capped near 15 seconds. Export IDs are checkpointed.',15,1,120),('maxExportJobs','Maximum planned source jobs','Fail before submission if advertiser × country × date chunks exceeds this number.',100,1,10000)]:field(k,t,'integer',d,default,minimum=lo,maximum=hi)
field('operationIds','Advanced export operation IDs','object','Optional create/status IDs from a permitted current public-page network capture. Never credentials. Normally discovered from live page assets.',editor='json')
field('proxyConfiguration','Proxy configuration','object','Off by default. Configure Apify datacenter proxies as the first escalation for permitted access. No identity cycling or CAPTCHA bypass.',{'useApifyProxy':False},editor='proxy')
write('.actor/input_schema.json',{'title':'X (Twitter) Ads Scraper & Competitor Monitor','type':'object','schemaVersion':1,'description':'Public EU-served X advertising transparency. Fields not disclosed are null with provenance; global ad-content discovery is unavailable.','properties':p})
write('.actor/actor.json',{'actorSpecification':1,'name':'x-twitter-ads-scraper','title':'X (Twitter) Ads Scraper & Competitor Monitor','description':'Extract publicly disclosed EU-served X ads, compare advertisers and countries, monitor material campaign changes, and export audit-friendly reports.','version':'1.0','buildTag':'latest','defaultMemoryMbytes':1024,'minMemoryMbytes':512,'maxMemoryMbytes':8192,'dockerfile':'./Dockerfile','readme':'../README.md','input':'./input_schema.json','output':'./output_schema.json','storages':{'dataset':'./dataset_schema.json'}})
write('.actor/output_schema.json',{'actorOutputSchemaVersion':1,'title':'X ad results and reports','properties':{
 'ads':{'type':'string','title':'Ads dataset','description':'One result per ad and served country. Monitor mode contains campaign events only.','template':'{{links.apiDefaultDatasetUrl}}/items'},
 **{k:{'type':'string','title':t,'description':d,'template':'{{links.apiDefaultKeyValueStoreUrl}}/records/'+key} for k,t,d,key in [('summary','Summary','Totals, source scope, query outcomes, schema drift, notifications and charged events.','SUMMARY'),('errors','Errors','Failures and quarantined rows; never mixed into the ads dataset.','ERRORS'),('csv','CSV download','UTF-8 BOM CSV; created when csv is selected.','ads.csv'),('json','JSON download','Normalized emitted ads; created when json is selected.','ads.json'),('xlsx','Excel workbook','Ads, Advertisers, Countries, Changes and Summary; created when xlsx is selected.','ads.xlsx'),('html','HTML report','Self-contained summary/charts/search/sort table; created when html is selected.','report.html')]}}})
# All output properties have field metadata. Null provenance is also available per path.
def prop(typ,desc,nullable=False,**kwargs): return {'type':[typ,'null'] if nullable else typ,'description':desc,**kwargs}
f={}
texts={'adKey':'SHA-1 of advertiser user ID, tweet ID, line-item ID and served country.','adId':'Repository ad identifier, or the tweet ID when no ad identifier is disclosed.','adIdSource':'repository or tweet_id_fallback.','tweetId':'Post ID preserved exactly as a string, never floating point.','lineItemId':'Disclosed advertising line-item ID.','accountId':'Disclosed advertising account ID; not necessarily the public user ID.','adName':'Derived name, never represented as a disclosed X campaign title.','adNameSource':'Name derivation: UTM campaign/content, creative headline, or identity.','adUrl':'Public post link.','adCreatedAt':'UTC post creation from Snowflake arithmetic, not campaign delivery start.','adCreatedAtSource':'derived_tweet_snowflake or invalid_or_pre_snowflake_id.','deliveryStart':'Disclosed delivery start, otherwise null; query window is not substituted.','deliveryStartSource':'Provenance for deliveryStart.','deliveryEnd':'Disclosed delivery end, otherwise null.','deliveryEndSource':'Provenance for deliveryEnd.','daysActiveSource':'Actual disclosed-date derivation or reason duration cannot be inferred.','firstSeenAt':'First observed timestamp; monitor state retains it across runs.','lastSeenAt':'Last observed timestamp, not the removal report timestamp.','scrapedAt':'UTC observation/run timestamp.','country':'ISO alpha-2 country where this ad was served.','countryName':'ISO regional display name.','countryNameSource':'ISO/Intl derived country name or unknown.','targetedLocationsStatus':'Whether geo-targeting was actually disclosed.','targetingStatus':'Whether targeting was actually disclosed.','targetingSummary':'Human-readable targeting string suitable for CSV.','impressionsStatus':'Repository count or aggregation/unknown reason.','reachStatus':'Repository reach or non-additive multi-chunk reason.','fundingStatus':'Disclosed funding coverage; missing nested fields carry availability reasons.','approvalStatus':'Source approval status preserved as disclosed.','approvalStatusSource':'Repository or not_disclosed.','isHaltedSource':'Explicit repository flag/status or reason unavailable.','changeStatus':'NEW, CHANGED, UNCHANGED or REMOVED.','schemaVersion':'Version of normalized output contract.'}
nullable={'accountId','adCreatedAt','deliveryStart','deliveryEnd','countryName','approvalStatus'}
for k,d in texts.items():f[k]=prop('string',d,k in nullable)
for k,d in {'daysActive':'Active days from disclosed delivery dates; unknown continuity is null.','impressions':'Observed impressions; may be summed only over disjoint queried date chunks.','reach':'Unique reach. Never summed across countries/chunks as if globally deduplicated.','impressionsLower':'Disclosed lower impression bound.','impressionsUpper':'Disclosed upper impression bound.','reachLower':'Disclosed lower reach bound, or lower union bound across chunks.','reachUpper':'Disclosed upper reach bound, or upper union bound across chunks.'}.items():f[k]=prop('number',d,True)
f['isHalted']=prop('boolean','True only when an explicit halted flag/status is disclosed; unknown is null.',True)
f['filterUncertain']=prop('boolean','One or more selected filters could not be decided from disclosed/enriched fields.')
for k,d in {'targetedLocations':'Disclosed geo-targeting names; distinct from served countries.','changedFields':'Material paths that changed relative to monitor state.','matchedKeywords':'Include expressions that actually matched known values.','matchedFields':'Known fields with positive keyword matches.'}.items():f[k]=prop('array',d,items=prop('string','A disclosed location, material field path or matched expression.'))
f['advertiser']=prop('object','Public advertiser account identity.',properties={k:prop('string',d,k!='userId') for k,d in {'handle':'Public handle, otherwise null for numeric-only inputs.','userId':'Exact public numeric user ID as a string.','name':'Public advertiser display name if resolved.','profileUrl':'Public profile URL if handle is known.'}.items()})
f['targeting']=prop('array','Disclosed targeting rules without inferred inclusions.',items=prop('object','One targeting rule.',properties={'type':prop('string','Disclosed targeting type.',True),'name':prop('string','Disclosed rule name.',True),'included':prop('boolean','Explicit inclusion/exclusion; null if not disclosed.',True)}))
f['funding']=prop('object','Disclosed funding instrument. No identification of natural persons.',properties={k:prop('string',d,True) for k,d in {'instrumentType':'Disclosed payment/funding instrument type.','currency':'Disclosed ISO currency.','entity':'Disclosed funding entity; never inferred from payment information.'}.items()})
creative={}
for k,d in {'text':'Disclosed/enriched public post text.','textSource':'repository, public_oembed, official_api or unavailable reason.','authorName':'Public post author display name.','authorNameSource':'Author-name provenance.','mediaType':'Disclosed asset type; unknown stays unknown.','mediaTypeSource':'Media-type provenance.','assetCountSource':'Observed asset-count provenance; missing assets never imply zero.','landingUrl':'Disclosed/resolved destination URL.','landingUrlStatus':'repository/resolved/unavailable/error reason.','landingDomain':'Host derived from landingUrl.','landingDomainSource':'Domain derivation/provenance.','enrichmentStatus':'ok, not_attempted, deleted_or_unavailable, protected, rate_limited or error.'}.items():creative[k]=prop('string',d,k in ['text','authorName','landingUrl','landingDomain'])
creative['assetCount']=prop('integer','Number of observed creative assets only when complete metadata is disclosed.',True)
creative['assets']=prop('array','Public asset metadata, never guessed from HTML decoration.',items=prop('object','One disclosed asset.',properties={k:prop('string' if k in ['type','url'] else 'number','Disclosed '+k+'; null if unavailable.',True) for k in ['type','url','width','height','durationMs']}))
for k in ['hashtags','mentions']:creative[k]=prop('array','Tokens extracted from known creative text.',items=prop('string','A public '+k[:-1]+'.'))
creative['utm']=prop('object','UTM query parameters from the known landing URL.',additionalProperties=prop('string','Observed UTM value.'))
f['creative']=prop('object','Creative enrichment is best effort; repository metrics survive unavailable posts.',properties=creative)
f['source']=prop('object','Source and query provenance.',properties={'adapter':prop('string','export, ui or api.'),'queryKey':prop('string','Latest contributing query identifier.'),'queryKeys':prop('array','All contributing disjoint query keys.',items=prop('string','Query key.')),'dateSemantics':prop('string','Source boundary behavior and any uncertainty.')})
for k,d in {'extra':'New/unmapped public source fields and aggregation notes.','raw':'Untouched source row only when includeRaw is enabled.','previous':'Previous material values for changedFields only.','availability':'Reason code for every null output path, including nested fields.'}.items():f[k]=prop('object',d,additionalProperties=True)
views={}
for key,title,fields in [('overview','Overview',['adName','advertiser.handle','country','approvalStatus','impressions','reach','daysActive','deliveryStart','deliveryEnd','adUrl']),('creatives','Creatives',['adName','advertiser.handle','creative.text','creative.mediaType','creative.assetCount','creative.landingUrl','creative.enrichmentStatus','adUrl']),('targeting','Targeting & reach',['advertiser.handle','country','targetingSummary','impressions','reach','reachLower','reachUpper','funding.instrumentType','funding.currency','funding.entity','approvalStatus']),('changes','Changes',['changeStatus','changedFields','previous','advertiser.handle','country','adName','firstSeenAt','lastSeenAt','adUrl'])]:
 views[key]={'title':title,'transformation':{'flatten':['advertiser','creative','funding','source'],'fields':fields},'display':{'component':'table','properties':{name:{'label':name.split('.')[-1],**({'format':'link'} if name in ['adUrl','creative.landingUrl'] else {})} for name in fields}}}
write('.actor/dataset_schema.json',{'actorSpecification':1,'fields':{'type':'object','properties':f,'required':['adKey','tweetId','lineItemId','country','advertiser','creative','availability']},'views':views})
write('.actor/store_metadata.json',{'title':'X (Twitter) Ads Scraper & Competitor Monitor','slug':'x-twitter-ads-scraper','seoDescription':'Inspect public EU-served X ads, compare competitor targeting and reach, monitor campaign changes, and download CSV, JSON, Excel and HTML reports.','keywords':['X','Twitter','ads library','ads transparency','competitor ads','DSA','X Ads Repository','ad monitoring','EU advertising','targeting','advertiser research','campaign changes','creative enrichment','CSV export','marketing intelligence'],'categories':['Social media','Marketing'],'recommendedRunOptions':{'memoryMbytes':1024,'timeoutSecs':3600},'suggestedPricing':{'ad-result':0.002,'creative-enriched':0,'apify-actor-start':0.05},'releaseStatus':'Live export/CSV and Store Console validation required before publication'})
write('example-input.json',{'advertisers':['Nike'],'countries':['FR'],'marketPreset':'Custom','startDate':'30 days','endDate':'0 days','sourceMode':'auto','maxItems':100,'concurrency':2,'enrichCreatives':True,'exportFormats':['csv','json','xlsx','html']})
